- commons-vfs2/src/main/java/org/apache/commons/vfs2/FileExtensionSelector.java
* Removed duplication from Constructors
* Removed unneeded check for `null` `HashSet` as it is constructed during object creation by the JVM at runtime.
* Optimized the comparison over the Constructor by converting all extensions to lowercase and using the `contains` method of a `Set`.
> More efficient comparison in FileExtensionSelector

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/ftp/FtpClientFactory.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/ftp/FtpFileSystemConfigBuilder.java
In PASV mode, the FTP server returns its server IP (eg. pasv_address in vsftpd.conf),
when clients are from different subnets through NAT, they expect different server IP.
This patch exposes the workaround in commons-ftp into commons-vfs:
* use EPSV mode instead of PASV mode, EPSV mode returns only server port
* use PASV mode but overwrite the returned server IP with HostnameResolver
> [VFS-660] expose workaround for connecting to FTP server from different subnets in PASV mode

- commons-vfs2/src/main/java/org/apache/commons/vfs2/impl/DefaultFileMonitor.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/impl/test/DefaultFileMonitorTests.java
The original code tried adding recursively the children twice - once in `doAddFile` and then again in `addFile` itself. This is now simplified.
Also fix a test which should work only in recursive mode and add another one.
> Simplify adding files to DefaultFileMonitor

- commons-vfs2/src/main/java/org/apache/commons/vfs2/FileContent.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/DefaultFileContent.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/util/MonitorInputStream.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/util/MonitorOutputStream.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/DefaultFileContentTest.java
Fixes https://issues.apache.org/jira/projects/VFS/issues/VFS-705.
> Add ability to specify buffer sizes

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/AbstractFileName.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/local/LocalFileName.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/AbstractFileNameTest.java
We hit the same issue as [VFS-325](https://issues.apache.org/jira/projects/VFS/issues/VFS-325) but not for local files but rather for Samba. Extracting the logic from `LocalFileName` to the base `AbstractFileName` fixes it for any provider.
> Fix AbstractFileName.getURI returning unencoded #-sign

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/sftp/SftpFileObject.java
This PR removes an unnecessary invocation of `SftpObject.getType()` by `refresh()`. 
This invocation causes performance degradation of `SftpFileObject.getChildren()` when `CacheStrategy.ON_RESOLVE` is in use as this forces a call to `refresh()`, which in turn calls `getType()`, making an additional `stat()` call to the SFTP server for each child.
> VFS-619 Fixes performance issue with SftpFileObject.getChildren()

- commons-vfs2/src/main/java/org/apache/commons/vfs2/util/MonitorInputStream.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/DefaultFileContentTest.java
Similar to https://github.com/apache/commons-vfs/pull/30. That PR fixed only the `read` overload which accepts a buffer but missed the one with no arguments. This PR fixes also the other case.
See https://issues.apache.org/jira/projects/VFS/issues/VFS-614.
> MonitorInputStream should not close the stream in "read"

- commons-vfs2/src/main/java/org/apache/commons/vfs2/Resources.properties
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/local/LocalFileNameParser.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/res/ResourceFileName.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/res/ResourceFileNameParser.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/res/ResourceFileProvider.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/res/test/ResSchemeTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/res/test/Vfs444TestCase.java
- src/site/xdoc/filesystems.xml
The correct URI syntax is now `res:[path]`. The current documentation states `res://[path]` but that does not work, it is also incorrect according to the URI specs.
The `[path]` for resource locations is always absolute, and should not start with a slash. With this change the same `[path]` can be used for the ResourceFileProvider and `ClassLoader.getResource(...)`.
> VFS-444: corrected ResourceFileProvider uri/path processing.

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/sftp/SftpFileSystem.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/sftp/SftpFileSystemConfigBuilder.java
One of our customer has an interesting sftp server.
The server does not allow any further channels to be established after the execution of the exec command (getUid()).
So it is not possible to do any filesystem operations, because at first the exec command is executed to test if exec is disabled.
Maybe the server things we try to break the security or something else.
So my idea to solve this problem is to make execDisabled configurable. This is done here.
> [SFTP] Configure whether exec detection is enabled

- .travis.yml
this project cannot pass travis since Jul 22, 2019.
If you do care about the error on openjdk-ea, you shall fix it.
If you do not care, then shall add openjdk-ea to allow_failures.
It is not recommended to keep project failing travis for such a long time (several months till today.)
> Fix travis-ci to make allow_failures: - openjdk-ea due to https://jira.apache.org/jira/browse/VFS-765

- .travis.yml
Hi.
I don't think commons-vfs can pass travis-ci on jdk14.
the problem is at least in WebdavProviderTestCase, which use jackrabbit-standalone-1.6.5.
I also doubt the possibility for jackrabbit for passing tests on jdk14.
So as I am not familiar with jackrabbit, I can only put jdk14 into allow-failure for now.
I also suggest making jackrabbit on travis-ci.
I can help making travis-ci scripts for jackrabbit, but I'd prefer asking about it on mailing list before I take actions.
> set openjdk14 to allow_failures

- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http/test/GetContentInfoFunctionalTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http4/test/Http4GetContentInfoTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http4s/test/Http4sGetContentInfoTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http5/test/Http5GetContentInfoTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http5s/test/Http5sGetContentInfoTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/https/test/GetContentInfoFunctionalTest.java
Some tests are failing because of the absence of the Http/Https proxy configure.
This is a fix for them.
> Add proxy config for some Http/Https test

- .github/workflows/maven.yml
As it's described here : [workflow syntax for github actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
`When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true`
I think we should continue our build process if some job was failed.
> Add fail-fast : false for github actions maven.yml

- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/zip/test/ParseXmlInZipTestCase.java
Some test's assert expect language is english, and these test are failing when jvm's default language is not en.
This is a fix by setting jvm's default language to en.
> Fix some test error when jvm's default language is not en

- commons-vfs2/src/main/resources/org/apache/commons/vfs2/impl/providers.xml
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/tar/test/CreateFileSystemTestCase.java
This is a fix for failures in `createFileSystem` with extensions of  `.tgz` and `.tbz2`.
> [VFS-769] Fix .tgz and .tbz2 createFileSystem fails

- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http5s/test/Http5sGetContentInfoTest.java
`org.apache.commons.vfs2.provider.http5s.test.Http5sGetContentInfoTest#testSSLGetContentInfo`  test fail caused by lack proxy configure. This PR is a fix for it.
> Fix test fail caused by lack proxy configuration for machines behind a proxy

- commons-vfs2-examples/src/main/java/org/apache/commons/vfs2/example/Shell.java
- commons-vfs2-jackrabbit1/src/main/java/org/apache/commons/vfs2/provider/webdav/WebdavFileObject.java
- commons-vfs2-jackrabbit2/src/main/java/org/apache/commons/vfs2/provider/webdav4/Webdav4FileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/FileSystemOptions.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/filter/WildcardFileFilter.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/impl/StandardFileSystemManager.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/impl/VFSClassLoader.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/AbstractFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/AbstractFileSystem.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/DefaultFileContent.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/DelegateFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/sftp/SftpFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/tar/TarFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/zip/ZipFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/util/Os.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/test/AbstractTestSuite.java
Use method with empty array instead of pre size array.
Because it's more safe and faster.
See also this [blog](https://shipilev.net/blog/2016/arrays-wisdom-ancients/)
> Modify some calls of method Collection.toArray

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/DefaultFileContent.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/FileContentThreadData.java
Don't create ArrayList instances that are never used.
> FileContentThreadData: lazy ArrayList initialization to save memory

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/http4/Http4FileProvider.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/http5/Http5FileProvider.java
VFS-785 e.g. if URI for root is https://github.com:8443/test.txt and proxy is github.com:3128 then credentials may get overridden in credential provider map
> [VFS-785] Credentials conflicting when root and proxy hosts are same name but different ports

- commons-vfs2/src/main/java/org/apache/commons/vfs2/cache/SoftRefFilesCache.java
This PR contains several commits which fix bugs in the SoftRefFilesCache locking code. There are quire a few race conditions and locking bugs. Additionally, it refactors the thread synchronization code to be easier, more robust and faster.
> Rework SoftRefFilesCache locking

- commons-vfs2/src/main/java/org/apache/commons/vfs2/VFS.java
[According to the documentation](https://github.com/apache/commons-vfs/blob/rel/commons-vfs-2.8.0/commons-vfs2/src/main/java/org/apache/commons/vfs2/VFS.java#L35), after `VFS.close` is called, calling `getManager` will create a new instance. That won't happen unless the instance is set to `null` first.
> Set `instance` to `null` after closing it

- commons-vfs2/src/main/java/org/apache/commons/vfs2/impl/DefaultFileSystemManager.java
Fixes https://issues.apache.org/jira/browse/VFS-796.
> Fix closing the files cache after warning that not all components have been closed

- commons-vfs2-jackrabbit1/src/test/java/org/apache/commons/vfs2/provider/webdav/test/WebdavProviderTestCase.java
- commons-vfs2-jackrabbit2/src/test/java/org/apache/commons/vfs2/provider/webdav4/test/Webdav4ProviderTestCase.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/local/LocalFile.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/tar/TarFileSystem.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/filter/BaseFilterTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/impl/DefaultFileMonitorTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/local/ConversionTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/tar/LargeTarTestCase.java
Use Files.newOutputStream instead of new FileOutputStream (fileName).
Use Files.newInputStream instead of new FileInputStream (fileName)
> Replace construction of FileInputStream and FileOutputStream objects with Files NIO APIs.

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/FileContentThreadData.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/DefaultFileContentTest.java
This is the workaround for the issue we spoke about in https://github.com/apache/commons-vfs/pull/166.
cc @garydgregory, @MaxKellermann
> Fix NPE when closing a stream from a different thread

- commons-vfs2/src/main/java/org/apache/commons/vfs2/auth/StaticUserAuthenticator.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/ftp/FtpFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/jar/JarFileSystem.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/tar/TarFileSystem.java
Reports unnecessary local variables, which add nothing to the comprehensibility of a method.
> VFS-801 - Redundant local variable

- README.md
This Pull Request is to update the Apache Commons VFS API Documentation link to the proper link, as the existing link results in a 404.
> (doc) Update the Javadoc link to not lead to 404.

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/sftp/SftpFileObject.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/sftp/AbstractSftpProviderTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/sftp/SftpPermissionExceptionTestCase.java
Try to copy a file from local to sftp server, if the sftp target directory can't write by the sftp user, it throw a exception as below.
```
Caused by: org.apache.commons.vfs2.FileSystemException: Could not write to "sftp://sftpuser:***@localhost/noperms/test.dat.tmp".
at org.apache.commons.vfs2.provider.AbstractFileObject.getOutputStream(AbstractFileObject.java:1270)
at org.apache.commons.vfs2.provider.DefaultFileContent.buildOutputStream(DefaultFileContent.java:540)
at org.apache.commons.vfs2.provider.DefaultFileContent.getOutputStream(DefaultFileContent.java:406)
at org.apache.commons.vfs2.provider.DefaultFileContent.getOutputStream(DefaultFileContent.java:394)
at org.apache.commons.vfs2.provider.DefaultFileContent.write(DefaultFileContent.java:815)
at …
```
> fix the sftp channel don't return to the pool when exception on  SftpFileObject.doGetOutputStream

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/ftp/FtpFileObject.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/ftp/FtpMdtmOnRefreshLastModifiedTests.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/ftp/FtpProviderMdtmOnRefreshTestCase.java
[VFS-814](https://issues.apache.org/jira/browse/VFS-814)
FtpFileObject.getTimestampMillis stores last modification time using FTPFile.setTimestamp.
doDetach() nulls out the underling FTPFile, but doesn't set mdtmSet = false this means later calls to FtpFileObject.getTimestampMillis fail to refresh mdtm and default to LIST timestamp.
---
Not sure what kind of testing you require for a patch this small?
> VFS-814 - FtpFileObject: re-fetch MDTM after refresh

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/sftp/SftpFileSystem.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/sftp/SftpFileSystemGroupsTests.java
id -g would return the gid 0
id -G however would return only a newline resulting in a NumberFormatException
> Handle the case where a user does not have any groups

- commons-vfs2/src/main/java/org/apache/commons/vfs2/impl/ProviderConfiguration.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/impl/StandardFileSystemManager.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/DelegateFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/hdfs/HdfsFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/ram/RamFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/sftp/SftpFileSystem.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/sftp/SftpFileSystemConfigBuilder.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/util/DefaultCryptor.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/util/DelegatingFileSystemOptionsBuilder.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/util/URIBitSets.java
- commons-vfs2/src/main/resources/org/apache/commons/vfs2/Resources.properties
- commons-vfs2/src/test/java/org/apache/commons/vfs2/ContentTests.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/LastModifiedTests.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/ProviderWriteAppendTests.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/ProviderWriteTests.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/operations/BasicOperationsTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http/HttpProviderTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http4/Http4ProviderTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http5/Http5ProviderTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/tar/TarFileSystemTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/util/DelegatingFileSystemOptionsBuilderTest.java
Fix various typos in code :
- private field or constant names,
- method attribute names,
- test class and method names,
- exception messages.
Those changes should not be problematic : they do not belog to the public API (except maybe the exception messages).
> Fix typos in code

- commons-vfs2/pom.xml
The hadoop-hdfs-client dependency isn't optional (and brings a whole bunch of dependencies in).
Since all the other hadoop dependencies (hadoop-common, hadoop-hdfs, etc) are optional I assume this was an oversight, so here's the PR to add it
> hadoop-hdfs-client is not set as optional

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/AbstractFileObject.java
> AbstractFileObject uses the wrong exception for "cause"

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/http/HttpFileObject.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/util/FileObjectUtils.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/impl/VfsClassLoaderTests.java
* To ensure that the closing of files does not interfere with
*   reading the content, the FileObjectUtils read methods must
*   be synchronized on the underlying filesystem just like the
*   close AbstractFileObject close and detach methods.
* Added a test case that demostrated the issue.
> [VFS-683] Class loader thread safety

- pom.xml
Dependabot did not pick this up for some reason
> Bump Hadoop client from 3.3.5 to 3.3.6

- commons-vfs2-jackrabbit2/src/main/java/org/apache/commons/vfs2/provider/webdav4/Webdav4FileObject.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/ProviderRenameTests.java
URIEncoded. Prevent that the urlString of a webdav-filename is twice URIEncoded when file is moved. Results in invalid filename if the filename contains spaces.
> VFS-844: Prevent that source files urlString is twice

- commons-vfs2/src/main/java/org/apache/commons/vfs2/impl/DefaultFileSystemManager.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/UriParser.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/impl/DefaultFileSystemManagerTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/UriParserTest.java
Fix that FileNames which are directories are resolved to FileType.FOLDER.
https://issues.apache.org/jira/browse/VFS-846
> VFS-846: Resolve a FileName to correct FileType

- commons-vfs2-jackrabbit2/src/main/java/org/apache/commons/vfs2/provider/webdav4/Webdav4FileObject.java
Instead of calling `((HttpRequestBase) request).releaseConnection()` directly after sending the request, encapsulate the HttpResponse in a try-with-resource block. This way, the connection is released after the HttpEntity is fully consumed.
> VFS-843: Close the HttpConnection after consuming the entire HttpEntity.

- commons-vfs2-jackrabbit1/src/test/java/org/apache/commons/vfs2/provider/webdav/test/WebdavProviderTestCase.java
- commons-vfs2-jackrabbit2/src/test/java/org/apache/commons/vfs2/provider/webdav4/test/Webdav4ProviderTestCase.java
- commons-vfs2-sandbox/src/test/java/org/apache/commons/vfs2/provider/smb/test/SmbProviderTestCase.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/HostFileNameParser.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/UriParser.java
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/http5/Http5FileObject.java
- commons-vfs2/src/main/resources/org/apache/commons/vfs2/Resources.properties
- commons-vfs2/src/test/java/org/apache/commons/vfs2/IPv6LocalConnectionTests.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/UriParserTest.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/ftp/FtpProviderIPv6TestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/ftp/FtpProviderTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http/HttpProviderTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http4/Http4ProviderTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/http5/Http5ProviderTestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/sftp/SftpProviderIPv6TestCase.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/test/GenericFileNameTest.java
https://issues.apache.org/jira/browse/VFS-524
The fix is based on the one, suggested in the Jira ticket, but also includes some corner cases covered and a number of additional unit tests, also tested end-to-end.
> [VFS-524] A URI with an IPv6 address can't be parsed out correctly

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/UriParser.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/NamingTests.java
Earlier, the path would be URL-decoded after normalization. This meant some opportunities for normalization would be missed when dots or slashes were URL-encoded.
One way to solve this would be to change the ordering of operations, but that seems risky as it would change the meaning of some of the abstractions. Because of that I opted for a more conservative approach, where normalization will take into account URL-encoded characters, but otherwise leave the input string intact.
> Support URLencoding during normalization

- commons-vfs2/pom.xml
- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/UriParser.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/NamingTests.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/UriParserBenchmark.java
- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/UriParserTest.java
- pom.xml
The reverts https://github.com/apache/commons-vfs/pull/396 and related
changes and implements the same in a simpler way by replacing the
encoded characters already in `fixSeparators`.
This approach has a slightly higher risk at breaking existing behaviour,
but a lower risk of remaining problems in this part of the codebase. All
testcases still succeed.
This PR is intended to replace https://github.com/apache/commons-vfs/pull/543 and https://github.com/apache/commons-vfs/pull/555. It includes the testcases
from https://github.com/apache/commons-vfs/pull/543, adapted to the behaviour before https://github.com/apache/commons-vfs/pull/396.
This reverts commit https://github.com/apache/commons-vfs/commit/cb45c9453669eb2570f582f491cb0e06b0e63466.
This reverts commit …
> Simplify UriParser

- commons-vfs2-sandbox/pom.xml
- commons-vfs2-sandbox/src/main/java/org/apache/commons/vfs2/provider/mime/MimeAttributesMap.java
- commons-vfs2-sandbox/src/main/java/org/apache/commons/vfs2/provider/mime/MimeFileContentInfoFactory.java
- commons-vfs2-sandbox/src/main/java/org/apache/commons/vfs2/provider/mime/MimeFileObject.java
- commons-vfs2-sandbox/src/main/java/org/apache/commons/vfs2/provider/mime/MimeFileSystem.java
- commons-vfs2-sandbox/src/main/java/org/apache/commons/vfs2/util/FileObjectDataSource.java
Fix for the sub-module `commons-vfs2-sandbox` not compiling
> Fixed commons-vfs sandbox module not compiling due to missing imports and library

- commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/ftp/FtpFileObject.java
Fixed consistency of wrongly using `java.io.FileNotFoundException` instead of much preferred `org.apache.commons.vfs2.FileNotFoundException`
> Fix consistency of wrongly used java.io.FileNotFoundException

- commons-vfs2/src/test/java/org/apache/commons/vfs2/provider/test/JunctionTests.java
The test would leave a file behind, causing it to fail the next time it runs (e.g. impacting 'mvn install')
> [VFS-856] Fix JunctionTests
